services:
  web-app:
    restart: always
    build:
      context: ./welbex
    ports:
      - "8000:8000"
    volumes:
      - ./welbex:/welbex
    depends_on:
      - database
      - redis

  database:
    image: postgres:14.4-alpine3.16
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=test_user
      - POSTGRES_PASSWORD=test_password
      - POSTGRES_DB=test_database
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7.0.5-alpine
    hostname: redis

  celery-worker:
    build:
      context: ./welbex
    hostname: worker
    entrypoint: celery
    command: -A welbex.celery_app.app worker --loglevel=info
    volumes:
      - ./welbex:/welbex
    links:
      - redis
    depends_on:
      - redis

  celery-beat:
    build:
      context: ./welbex
    hostname: beat
    entrypoint: celery
    command: -A welbex.celery_app.app beat --loglevel=info
    volumes:
      - ./welbex:/welbex
    links:
      - redis
    depends_on:
      - redis