# Generated by Django 4.2.1 on 2023-05-28 13:55

import common.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.PositiveIntegerField(validators=[common.validators.validate_range])),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('delivery_location', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='delivery', to='location.location')),
                ('pick_up_location', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='pick_up', to='location.location')),
            ],
            options={
                'db_table': 'cargo',
            },
        ),
    ]
