# Generated by Django 4.2.1 on 2023-05-28 13:55

import car.validators
import common.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=5, unique=True, validators=[car.validators.validate_car_number])),
                ('load_capacity', models.PositiveIntegerField(validators=[common.validators.validate_range])),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='location.location')),
            ],
            options={
                'db_table': 'car',
            },
        ),
    ]
